server:
  port: 8088
ip: 1.1.1.1
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/play?useUnicode=true&characterEncoding=utf-8
  username: root
  password:

phone:
  color: blue

nba:
  players:
    - abc
    - defg
    - hello

phones:
  - xiaomi
  - apple